### ISSUE TITLE
__init__.py导包报错

### ISSUE THREAD

**Issue by satangele** [helloflask/flask-dropzone#64]
Flask已经没有Markup模块，需要从markupsafe中导入

**Comment by yuxiaoy1** [comment]
这个问题已经通过 https://github.com/helloflask/flask-dropzone/pull/63 解决。是否可以发布一个新版本? @greyli

**Comment by greyli** [comment]
> 这个问题已经通过 #63 解决。是否可以发布一个新版本? @greyli

Thanks, I have invited you as the PyPI maintainer. You could try to make a new fix release, thanks!

**Comment by greyli** [comment]
[2.0.0 version](https://github.com/helloflask/flask-dropzone/releases/tag/2.0.0) released.
